services:
  - type: web
    name: customer-intelligence-api
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: MODEL_PATH
        value: ml/artifacts/random_forest_reorder_model.joblib
      - key: MODEL_URI
        sync: false
      - key: MODEL_RUN_HISTORY_TABLE
        value: CUSTOMER_INTELLIGENCE.ML_ARTIFACTS.MODEL_TRAINING_RUNS
      - key: OPENAI_MODEL
        value: gpt-4.1-mini
      - key: SNOWFLAKE_ACCOUNT
        sync: false
      - key: SNOWFLAKE_USER
        sync: false
      - key: SNOWFLAKE_PASSWORD
        sync: false
      - key: SNOWFLAKE_ROLE
        sync: false
      - key: SNOWFLAKE_WAREHOUSE
        sync: false
      - key: SNOWFLAKE_DATABASE
        sync: false
      - key: SNOWFLAKE_SCHEMA
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
